<?php

return [
    'What was the name of your childhood best friend?',
    'What was your favorite book as a child?',
    'What was the name of your first stuffed animal?',
    'What was your childhood nickname?',
    'What street did you grow up on?',
    'Who was your favorite teacher in high school?',
    'What was the name of your first pet?',
    'What was your dream job as a child?',
    'Where did your parents meet?',
    'What was your first car?',
    'What color was your childhood bedroom?',
    'What was the name of your first roommate?',
    'What is your mother’s middle name?',
    'What was your father’s profession?',
    'Where did you go on your first holiday?',
    'What was the name of your first boss?',
    'What’s your maternal grandmother’s first name?',
    'What’s your paternal grandfather’s first name?',
    'Where were you when you first heard about 9/11?',
    'What city were you in during your first heartbreak?',
    'What was the name of your favorite childhood toy?',
    'What’s your oldest cousin’s first name?',
    'What’s the name of your favorite high school friend?',
    'What was the name of your favorite restaurant as a teen?',
    'What instrument did you play in school?',
    'What was the model of your first phone?',
    'Who was your childhood celebrity crush?',
    'What’s the name of your favorite teacher of all time?',
    'What game did you play most as a child?',
    'What year did you graduate primary school?',
    'What was the name of the park you visited most as a child?',
    'What was the name of your kindergarten teacher?',
    'What’s the name of the first person you kissed?',
    'What was your first email address?',
    'What was the first website you visited regularly?',
    'What was your favorite cartoon growing up?',
    'What was your favorite ice cream flavor as a kid?',
    'Who taught you how to ride a bike?',
    'What was the name of your childhood doctor?',
    'What’s the name of the first country you visited?',
    'What was your childhood home’s house number?',
    'What’s the name of the first movie you saw in a cinema?',
    'What was the first video game you played?',
    'What’s the name of the store your family shopped at weekly?',
    'What was your first job?',
    'What’s the name of the first school you attended?',
    'What was the title of your favorite book in secondary school?',
    'What is the name of the town your mother was born in?',
    'What was your favorite school subject?',
    'Who was your first best friend in university?',
    'What sport did you play most in high school?',
    'What’s the name of your first boss?',
    'What’s your father’s nickname?',
    'What was the name of the street your best friend lived on?',
    'What was the name of your first love?',
    'What day of the week were you born?',
    'What is your uncle’s middle name?',
    'What was your first job title?',
    'What food did you hate as a child?',
    'What was your favorite video game in high school?',
    'What kind of music did your parents play in the house?',
    'What was your first mobile number?',
    'What was the make of your first laptop?',
    'What was the name of the teacher who taught you math in SS1?',
    'What book changed your life in secondary school?',
    'What’s the name of your favorite aunt?',
    'What nickname did your neighbors call you?',
    'Where did you spend most of your school holidays?',
    'What is the name of your father’s best friend?',
    'What’s the name of the church or mosque you attended as a child?',
    'What festival did you attend every year as a child?',
    'What chore did you hate doing as a child?',
    'What was the name of your first crush in primary school?',
    'What toy did you never let anyone touch?',
    'What’s the name of your childhood barber or hairdresser?',
    'What traditional dish reminds you of home?',
    'What name did your grandparents call you?',
    'What’s the name of the first pet you lost?',
    'What was your first school uniform color?',
    'What book series did you read as a child?',
    'Who was your favorite family member growing up?',
    'What’s the name of your favorite science teacher?',
    'What TV show did your family watch together?',
    'What was your first nickname online or in games?',
    'Where did you go during your first school excursion?',
    'What’s the first city you visited without your parents?',
    'Who inspired you most during your teenage years?',
    'What club or society were you most active in at school?',
    'What animal did you fear as a child?',
    'Who gave you your first birthday gift?',
    'What’s the name of the driver who used to take you to school?',
    'What’s the name of your family’s favorite local hangout spot?',
    'What was your father’s car plate number?',
    'What’s the name of your first tutor outside of school?',
    'What was your mother’s favorite food when you were a child?',
    'What’s the name of your school’s head teacher during JS1?',
    'What app did you use most in your first smartphone?',
    'What language did you first learn to speak?',
    'What song reminds you of your first relationship?',
    'What was the first cultural event you performed at?',
    'Who gave you your first nickname?',
    'What school did you attend for nursery education?',
    'What name did your favorite teacher call you by?',
    'What was the name of the hospital you had your first injection in?',
    'Who bought you your first school bag?',
];

