name: Laravel Backend CI/CD

on:
  push:
    branches:
      - 'master'
      - 'staging'
      - 'dev'
      - 'feature/*'

env:
  IMAGE_URI: "820242924853.dkr.ecr.eu-west-2.amazonaws.com/backend"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    name: Build and Push Docker Image

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Export AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Authenticate to AWS ECR
        run: aws ecr get-login-password --region eu-west-2 | docker login --username AWS --password-stdin $IMAGE_URI

      - name: Extract short commit SHA
        run: echo "short_commit_sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Determine tag
        run: |
          if [[ $GITHUB_REF == refs/heads/master ]]; then
            echo "tag=${short_commit_sha}-prod" >> $GITHUB_ENV
          elif [[ $GITHUB_REF == refs/heads/staging ]]; then
            echo "tag=${short_commit_sha}-stg" >> $GITHUB_ENV
          elif [[ $GITHUB_REF == refs/heads/dev ]]; then
            echo "tag=${short_commit_sha}-dev" >> $GITHUB_ENV
          else
            echo "tag=${short_commit_sha}" >> $GITHUB_ENV
          fi

      - name: Build Docker image
        run: docker build -t $IMAGE_URI:${{ env.tag }} .

      - name: Push Docker image
        run: docker push $IMAGE_URI:${{ env.tag }}

  check-for-leaked-secrets:
    runs-on: ubuntu-latest
    container:
      image: zricethezav/gitleaks:v8.26.0
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Python
        run: |
          apk update
          apk add --no-cache python3 py3-pip

      - name: Disable Git ownership check
        run: git config --global --add safe.directory "*"

      - name: Scan the code
        run: gitleaks detect --verbose --source . -f json -r gitleaks.json

      - name: Upload to DefectDojo
        if: failure()
        env:
          DEFECT_DOJO_FILE: gitleaks.json
          DEFECT_DOJO_ENGAGEMENT: 1
          DEFECT_DOJO_API_TOKEN: ${{ secrets.DEFECT_DOJO_API_TOKEN }}
          DEFECT_DOJO_SCAN_TYPE: Gitleaks Scan
          DEFECT_DOJO_URL: https://defectdojo.travimobile.com/api/v2/import-scan/
          DEFECT_DOJO_PRODUCT_NAME: Backend
        run: python upload-scan-report.py

  dependency-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install PHP dependencies
        run: composer install --no-interaction --prefer-dist --no-dev

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install JS dependencies
        run: npm install

      - name: Install dependency-check
        run: |
          chmod +x dependency-check.sh
          ./dependency-check.sh

      - name: Run dependency-check
        run: |
          mkdir -p ./dc-data ./reports
          dependency-check \
            --nvdApiDelay 7000 \
            --nvdApiKey ${{ secrets.NVD_API }} \
            --data ./dc-data \
            --scan . \
            --log ./reports/dependency-check.log \
            --enableExperimental \
            --format JSON \
            --format XML \
            --failOnCVSS 4.0 \
            --out reports/

      - name: Upload to DefectDojo
        if: failure()
        env:
          DEFECT_DOJO_FILE: ./reports/dependency-check-report.xml
          DEFECT_DOJO_ENGAGEMENT: 1
          DEFECT_DOJO_API_TOKEN: ${{ secrets.DEFECT_DOJO_API_TOKEN }}
          DEFECT_DOJO_SCAN_TYPE: Dependency Check Scan
          DEFECT_DOJO_URL: https://defectdojo.travimobile.com/api/v2/import-scan/
          DEFECT_DOJO_PRODUCT_NAME: Backend
        run: python upload-scan-report.py

  sast-scan:
    runs-on: ubuntu-latest
    container:
      image: semgrep/semgrep
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Semgrep
        run: semgrep scan --config=auto --error --json --output semgrep.json

      - name: Upload to DefectDojo
        if: failure()
        env:
          DEFECT_DOJO_FILE: semgrep.json
          DEFECT_DOJO_ENGAGEMENT: 1
          DEFECT_DOJO_API_TOKEN: ${{ secrets.DEFECT_DOJO_API_TOKEN }}
          DEFECT_DOJO_SCAN_TYPE: Semgrep JSON Report
          DEFECT_DOJO_URL: https://defectdojo.travimobile.com/api/v2/import-scan/
          DEFECT_DOJO_PRODUCT_NAME: Backend
        run: python upload-scan-report.py

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, intl
          tools: composer

      - name: Install dependencies
        run: composer install

      - name: Set up .env
        run: cp .env.example .env && php artisan key:generate

      - name: Run Unit Tests
        run: php artisan test
