name: Build and Push Travi Backend Image to Docker Hub

on:
  push:
    branches: [ master, staging, dev ]

env:
  IMAGE_NAME: travi3/travimobile-backend-nginx

jobs:
  build-image:
    runs-on: ubuntu-latest
    name: Build and push Docker image to Docker Hub

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure full git history for proper SHA

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Set up tags
        id: set-tags
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "short_commit_sha=$SHORT_SHA" >> $GITHUB_ENV
          
          if [[ "$GITHUB_REF" == "refs/heads/master" ]]; then
            echo "TAG=${SHORT_SHA}-prod" >> $GITHUB_ENV
          elif [[ "$GITHUB_REF" == "refs/heads/staging" ]]; then
            echo "TAG=${SHORT_SHA}-stg" >> $GITHUB_ENV
          elif [[ "$GITHUB_REF" == "refs/heads/dev" ]]; then
            echo "TAG=${SHORT_SHA}-dev" >> $GITHUB_ENV
          fi
          
          echo "Using tag: $TAG"

      - name: Build Docker image
        run: docker build -f Dockerfile.nginx -t $IMAGE_NAME:${{ env.TAG }} .

      - name: Push Docker image to Docker Hub
        run: docker push $IMAGE_NAME:${{ env.TAG }}

      - name: Logout from Docker Hub
        if: always()
        run: docker logout