name: Build and Push Travi Backend Image to Docker Hub

on:
  push:
    branches: [ master, staging, dev ]

env:
  IMAGE_NAME: travi3/travimobile-backend-nginx

jobs:
  build-image:
    runs-on: ubuntu-latest
    name: Build and push Docker image to Docker Hub

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Extract short commit SHA
        id: vars
        run: echo "short_commit_sha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Determine tag
        id: tag
        run: |
          if [[ $GITHUB_REF == refs/heads/master ]]; then
            echo "tag=${{ env.short_commit_sha }}-prod" >> $GITHUB_ENV
          elif [[ $GITHUB_REF == refs/heads/staging ]]; then
            echo "tag=${{ env.short_commit_sha }}-stg" >> $GITHUB_ENV
          elif [[ $GITHUB_REF == refs/heads/dev ]]; then
            echo "tag=${{ env.short_commit_sha }}-dev" >> $GITHUB_ENV
          fi

      - name: Build Docker image
        run: docker build -f Dockerfile.nginx -t $IMAGE_NAME:${{ env.tag }} .

      - name: Push Docker image to Docker Hub
        run: docker push $IMAGE_NAME:${{ env.tag }}

      - name: Logout from Docker Hub
        if: always()
        run: docker logout
