name: Build and Push Backend Nginx Image

on:
  push:
    branches: [ master, staging, dev ]
  workflow_dispatch:

jobs:
  build-and-push:
    uses: Travimobile-Engineering/shared-workflows/.github/workflows/reusable-docker-build.yml@main
    with:
      image-name: "travi3/backend-nginx"
      build-nginx: true
      main-branch-name: "master"
      use-sha-tags: true
    secrets:
      docker-username: ${{ secrets.DOCKER_USERNAME }}
      docker-token: ${{ secrets.DOCKER_TOKEN }}